sonar.projectKey=qrypta-bastion-proyect
sonar.projectName=Qrypta Bastion Proyect
sonar.sources=qrypta/cliente_movil/lib,qrypta/cliente_web/src,qrypta/cliente_escritorio/src,qrypta/servidor/dashboard_admin_web/src
sonar.tests=qrypta/cliente_movil/test,qrypta/cliente_movil/integration_test,qrypta/cliente_web/src,qrypta/cliente_escritorio/src,qrypta/servidor/dashboard_admin_web/src
sonar.test.inclusions=**/*test*.dart,**/*.test.ts,**/*.test.tsx,**/integration_test/**/*.dart
sonar.exclusions=**/build/**,**/dist/**,**/.dart_tool/**,**/node_modules/**
sonar.sourceEncoding=UTF-8
